/** Türkiye — 81 il (alfabetik) */
export const TURKEY_PROVINCES: string[] = [
  'Adana',
  'Adıyaman',
  'Afyonkarahisar',
  'Ağrı',
  'Aksaray',
  'Amasya',
  'Ankara',
  'Antalya',
  'Ardahan',
  'Artvin',
  'Aydın',
  'Balıkesir',
  'Bartın',
  'Batman',
  'Bayburt',
  'Bilecik',
  'Bingöl',
  'Bitlis',
  'Bolu',
  'Burdur',
  'Bursa',
  'Çanakkale',
  'Çankırı',
  'Çorum',
  'Denizli',
  'Diyarbakır',
  'Düzce',
  'Edirne',
  'Elazığ',
  'Erzincan',
  'Erzurum',
  'Eskişehir',
  'Gaziantep',
  'Giresun',
  'Gümüşhane',
  'Hakkâri',
  'Hatay',
  'Iğdır',
  'Isparta',
  'İstanbul',
  'İzmir',
  'Kahramanmaraş',
  'Karabük',
  'Karaman',
  'Kars',
  'Kastamonu',
  'Kayseri',
  'Kırıkkale',
  'Kırklareli',
  'Kırşehir',
  'Kilis',
  'Kocaeli',
  'Konya',
  'Kütahya',
  'Malatya',
  'Manisa',
  'Mardin',
  'Mersin',
  'Muğla',
  'Muş',
  'Nevşehir',
  'Niğde',
  'Ordu',
  'Osmaniye',
  'Rize',
  'Sakarya',
  'Samsun',
  'Siirt',
  'Sinop',
  'Sivas',
  'Şanlıurfa',
  'Şırnak',
  'Tekirdağ',
  'Tokat',
  'Trabzon',
  'Tunceli',
  'Uşak',
  'Van',
  'Yalova',
  'Yozgat',
  'Zonguldak',
]

/** Popüler ülkelerin ana şehirleri */
export const COUNTRY_CITIES: Record<string, string[]> = {
  Türkiye: TURKEY_PROVINCES,
  Almanya: [
    'Berlin',
    'Münih',
    'Hamburg',
    'Frankfurt',
    'Köln',
    'Stuttgart',
    'Düsseldorf',
    'Dortmund',
    'Essen',
    'Leipzig',
    'Bremen',
    'Dresden',
    'Hannover',
    'Nürnberg',
  ],
  'Amerika Birleşik Devletleri': [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Miami',
    'San Francisco',
    'Seattle',
    'Boston',
    'Washington',
    'Dallas',
    'Atlanta',
    'Philadelphia',
    'Phoenix',
    'Denver',
    'Las Vegas',
  ],
  İngiltere: [
    'Londra',
    'Manchester',
    'Birmingham',
    'Liverpool',
    'Leeds',
    'Glasgow',
    'Edinburgh',
    'Bristol',
    'Sheffield',
    'Nottingham',
  ],
  Fransa: [
    'Paris',
    'Marsilya',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Bordeaux',
    'Lille',
  ],
  İtalya: [
    'Roma',
    'Milano',
    'Napoli',
    'Torino',
    'Palermo',
    'Bologna',
    'Floransa',
    'Venedik',
    'Verona',
    'Cenova',
  ],
  Hollanda: [
    'Amsterdam',
    'Rotterdam',
    'Lahey',
    'Utrecht',
    'Eindhoven',
    'Groningen',
    'Tilburg',
  ],
  Azerbaycan: [
    'Bakü',
    'Gence',
    'Sumgayıt',
    'Mingaçevir',
    'Şeki',
    'Lenkeran',
  ],
  İspanya: [
    'Madrid',
    'Barselona',
    'Valencia',
    'Sevilla',
    'Bilbao',
    'Malaga',
    'Saragossa',
  ],
  Rusya: [
    'Moskova',
    'Saint Petersburg',
    'Kazan',
    'Novosibirsk',
    'Yekaterinburg',
    'Soçi',
  ],
  Japonya: [
    'Tokyo',
    'Osaka',
    'Yokohama',
    'Nagoya',
    'Sapporo',
    'Kyoto',
    'Fukuoka',
  ],
  Çin: [
    'Pekin',
    'Şangay',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Hangzhou',
    'Wuhan',
  ],
  Kanada: [
    'Toronto',
    'Vancouver',
    'Montreal',
    'Calgary',
    'Ottawa',
    'Edmonton',
    'Quebec',
  ],
  Avustralya: [
    'Sidney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Canberra',
  ],
  Belçika: ['Brüksel', 'Anvers', 'Gent', 'Brugge', 'Liège'],
  İsviçre: ['Zürih', 'Cenevre', 'Basel', 'Bern', 'Lozan'],
  Avusturya: ['Viyana', 'Graz', 'Linz', 'Salzburg', 'Innsbruck'],
  İsveç: ['Stockholm', 'Göteborg', 'Malmö', 'Uppsala'],
  Norveç: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'],
  Danimarka: ['Kopenhag', 'Aarhus', 'Odense', 'Aalborg'],
  Finlandiya: ['Helsinki', 'Espoo', 'Tampere', 'Turku'],
  Polonya: ['Varşova', 'Kraków', 'Wrocław', 'Gdańsk', 'Poznań'],
  Ukrayna: ['Kiev', 'Kharkiv', 'Odessa', 'Lviv', 'Dnipro'],
  Yunanistan: ['Atina', 'Selanik', 'Patras', 'Heraklion'],
  Portekiz: ['Lizbon', 'Porto', 'Braga', 'Coimbra'],
  İrlanda: ['Dublin', 'Cork', 'Galway', 'Limerick'],
  Macaristan: ['Budapeşte', 'Debrecen', 'Szeged'],
  Romanya: ['Bükreş', 'Cluj-Napoca', 'Timișoara', 'Iași'],
  Bulgaristan: ['Sofya', 'Plovdiv', 'Varna', 'Burgas'],
  Sırbistan: ['Belgrad', 'Novi Sad', 'Niš'],
  Hırvatistan: ['Zagreb', 'Split', 'Rijeka', 'Dubrovnik'],
  Gürcistan: ['Tiflis', 'Batumi', 'Kutaisi'],
  Kazakistan: ['Astana', 'Almatı', 'Şımkent', 'Karaganda'],
  Özbekistan: ['Taşkent', 'Semerkant', 'Buhara', 'Namangan'],
  Türkmenistan: ['Aşkabat', 'Türkmenabat', 'Daşoguz'],
  Kırgızistan: ['Bişkek', 'Oş', 'Jalal-Abad'],
  Irak: ['Bağdat', 'Basra', 'Erbil', 'Musul'],
  İran: ['Tahran', 'İsfahan', 'Şiraz', 'Tebriz', 'Meşhed'],
  Suriye: ['Şam', 'Halep', 'Homs', 'Lazkiye'],
  Lübnan: ['Beyrut', 'Tripoli', 'Sidon'],
  Ürdün: ['Amman', 'Zarqa', 'Irbid'],
  'Suudi Arabistan': ['Riyad', 'Cidde', 'Mekke', 'Medine', 'Dammam'],
  'Birleşik Arap Emirlikleri': [
    'Dubai',
    'Abu Dabi',
    'Şarika',
    'Ajman',
    'Ras Al Khaimah',
  ],
  Katar: ['Doha', 'Al Wakrah', 'Al Khor'],
  Kuveyt: ['Kuveyt', 'Hawalli', 'Salmiya'],
  Mısır: ['Kahire', 'İskenderiye', 'Giza', 'Luxor', 'Asvan'],
  Fas: ['Kazablanka', 'Rabat', 'Marakeş', 'Fes', 'Tanca'],
  Cezayir: ['Cezayir', 'Oran', 'Constantine', 'Annaba'],
  Tunus: ['Tunus', 'Sfax', 'Sousse', 'Kairouan'],
  Libya: ['Trablus', 'Bingazi', 'Misrata'],
  'Güney Afrika': [
    'Johannesburg',
    'Cape Town',
    'Durban',
    'Pretoria',
    'Port Elizabeth',
  ],
  Nijerya: ['Lagos', 'Abuja', 'Kano', 'Ibadan'],
  Kenya: ['Nairobi', 'Mombasa', 'Kisumu'],
  Hindistan: [
    'Yeni Delhi',
    'Mumbai',
    'Bangalore',
    'Kalküta',
    'Chennai',
    'Hyderabad',
  ],
  Pakistan: ['İslamabad', 'Karaçi', 'Lahor', 'Faisalabad'],
  Bangladeş: ['Dakka', 'Chittagong', 'Khulna'],
  Endonezya: ['Cakarta', 'Surabaya', 'Bandung', 'Bali', 'Medan'],
  Malezya: ['Kuala Lumpur', 'George Town', 'Johor Bahru'],
  Singapur: ['Singapur'],
  Tayland: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya'],
  Vietnam: ['Ho Chi Minh', 'Hanoi', 'Da Nang', 'Hai Phong'],
  Filipinler: ['Manila', 'Cebu', 'Davao', 'Quezon City'],
  'Güney Kore': ['Seul', 'Busan', 'Incheon', 'Daegu', 'Gwangju'],
  Brezilya: [
    'São Paulo',
    'Rio de Janeiro',
    'Brasília',
    'Salvador',
    'Fortaleza',
  ],
  Arjantin: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza'],
  Şili: ['Santiago', 'Valparaíso', 'Concepción'],
  Kolombiya: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla'],
  Meksika: [
    'Mexico City',
    'Guadalajara',
    'Monterrey',
    'Cancún',
    'Tijuana',
  ],
  Peru: ['Lima', 'Arequipa', 'Trujillo', 'Cusco'],
  'Yeni Zelanda': ['Auckland', 'Wellington', 'Christchurch', 'Queenstown'],
}

/** Haritada tanımlı olmayan ülkeler için yedek şehir listesi */
export const FALLBACK_CITIES = [
  'Başkent',
  'Merkez',
  'Kuzey Bölgesi',
  'Güney Bölgesi',
  'Doğu Bölgesi',
  'Batı Bölgesi',
  'Ana Şehir',
  'Büyükşehir',
  'Sahil Bölgesi',
  'İç Bölge',
]
