/** Tüm filtre panellerinde “filtreyi kaldır” seçeneği */
export const RANKINGS_FILTER_ALL_LABEL = 'TÜMÜ'

export const RANKINGS_GENDER_OPTIONS = ['Erkek', 'Kadın', 'Diğer']

export const RANKINGS_AGE_GROUPS = [
  '18-25',
  '26-35',
  '36-45',
  '46+',
]

export const RANKINGS_MARITAL_OPTIONS = ['Bekar', 'Evli']

/** Statik dünya ülkeleri listesi (Türkçe) */
export const WORLD_COUNTRIES = [
  'Türkiye',
  'Almanya',
  'Amerika Birleşik Devletleri',
  'İngiltere',
  'Fransa',
  'İtalya',
  'Hollanda',
  'Azerbaycan',
  'İspanya',
  'Rusya',
  'Japonya',
  'Çin',
  'Kanada',
  'Avustralya',
  'Belçika',
  'İsviçre',
  'Avusturya',
  'İsveç',
  'Norveç',
  'Danimarka',
  'Finlandiya',
  'Polonya',
  'Ukrayna',
  'Yunanistan',
  'Portekiz',
  'İrlanda',
  'Macaristan',
  'Romanya',
  'Bulgaristan',
  'Sırbistan',
  'Hırvatistan',
  'Gürcistan',
  'Kazakistan',
  'Özbekistan',
  'Türkmenistan',
  'Kırgızistan',
  'Irak',
  'İran',
  'Suriye',
  'Lübnan',
  'Ürdün',
  'Suudi Arabistan',
  'Birleşik Arap Emirlikleri',
  'Katar',
  'Kuveyt',
  'Mısır',
  'Fas',
  'Cezayir',
  'Tunus',
  'Libya',
  'Güney Afrika',
  'Nijerya',
  'Kenya',
  'Hindistan',
  'Pakistan',
  'Bangladeş',
  'Endonezya',
  'Malezya',
  'Singapur',
  'Tayland',
  'Vietnam',
  'Filipinler',
  'Güney Kore',
  'Brezilya',
  'Arjantin',
  'Şili',
  'Kolombiya',
  'Meksika',
  'Peru',
  'Yeni Zelanda',
]

/** Geniş meslek havuzu */
export const RANKINGS_PROFESSION_POOL = [
  'Avukat',
  'Aşçı',
  'Bankacı',
  'Berber',
  'Biyolog',
  'Doktor',
  'Eczacı',
  'Emlakçı',
  'Emekli',
  'Ev hanımı',
  'Esnaf',
  'Finans Uzmanı',
  'Gazeteci',
  'Girişimci',
  'Grafik Tasarımcı',
  'Hemşire',
  'İnsan Kaynakları Uzmanı',
  'İşletmeci',
  'Kasiyer',
  'Kuaför',
  'Kurye',
  'Memur',
  'Mimar',
  'Mühendis',
  'Müzisyen',
  'Muhasebeci',
  'Öğrenci',
  'Öğretmen',
  'Pazarlamacı',
  'Pilot',
  'Polis',
  'Psikolog',
  'Satış Temsilcisi',
  'Serbest Meslek',
  'Sosyal Medya Uzmanı',
  'Şoför',
  'Tasarımcı',
  'Teknisyen',
  'Turizm',
  'Veteriner',
  'Yazar',
  'Yazılımcı',
  'Ziraat Mühendisi',
]
